language: python

python:
  - 3.7
  - 3.8

before_install:
  - sudo curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/etc/poetry sudo python

install: sudo /etc/poetry/bin/poetry install

script: /etc/poetry/bin/poetry run py.test
